severity = 5
#BRUTAL!!!

# Keep the severity assignments for specific policies but REMOVE all exemptions
[TestingAndDebugging::RequireUseStrict]
severity = 5
[TestingAndDebugging::RequireUseWarnings]
severity = 5
[Variables::ProhibitPackageVars]
severity = 2
