#!/usr/bin/env perl
use strict;
use warnings;
use Carp;
use English qw(-no_match_vars $ERRNO $EVAL_ERROR $INPUT_RECORD_SEPARATOR $OS_ERROR $PROGRAM_NAME);
use locale;
use IPC::Open3;

my $main_exit_code = 0;
my $ls_success     = 0;
my $__set_e        = 0;
my $output         = q{};
our $CHILD_ERROR;

if (!(!(do {
    open my $original_stdout, '>&', STDOUT
      or die "Cannot save STDOUT: $OS_ERROR\n";
    open STDOUT, '>', '/dev/null'
      or die "Cannot open file: $OS_ERROR\n";
local *STDERR;
open STDERR, '>&', STDOUT or die "Cannot dup stderr: $OS_ERROR\n";
    my $tmp = do {
    $main_exit_code = system('gpg', '--version') >> 8;
    };
    print $tmp;
    open STDOUT, '>&', $original_stdout
      or die "Cannot restore STDOUT: $OS_ERROR\n";
    close $original_stdout
      or die "Close failed: $OS_ERROR\n";
};))) {
    print "GnuPG not available!\n";
exit 1;
}
{
    my $output_0 = q{};
    my $output_printed_0;
    my $pipeline_success_0 = 1;
        my ($in_1, $out_1);
    my $pid_1 = open3($in_1, $out_1, '>&STDERR', 'gpg', '--dry-run', '--with-fingerprint', '--with-colons');
    close $in_1 or croak 'Close failed: $OS_ERROR';
    $output_0 = do { local $INPUT_RECORD_SEPARATOR = undef; <$out_1> };
    close $out_1 or croak 'Close failed: $OS_ERROR';
    waitpid $pid_1, 0;

        my @lines = split /\n/msx, $output_0;
    my @result;
    foreach my $line (@lines) {
    chomp $line;
    if ($line =~ /^\s*$/msx) { next; }
    my @fields = split /\s+/msx, $line;
    if (!(BEGIN)) { next; }
    push @result, (f "# Ownertrust listing generated by lspgpot
    "
    printf "# This can be imported using the command:
    "
    printf "#    gpg --import-ownertrust
    "  }
    $fields[0] == "fpr" { fpr = $fields[9] }
    $fields[0] == "rtv" && $fields[1] == 1 && $fields[2] == 2 { printf "%s:3:
    " . fpr; next }
    $fields[0] == "rtv" && $fields[1] == 1 && $fields[2] == 5 { printf "%s:4:
    " . fpr; next }
    $fields[0] == "rtv" && $fields[1] == 1 && $fields[2] == 6 { printf "%s:5:
    " . fpr; next . "\n");
    }
    $output_0 = join "", @result;
    if ($output_0 ne q{} && !defined $output_printed_0) {
        print $output_0;
        if (!($output_0 =~ m{\n\z}msx)) {
            print "\n";
        }
    }
    if ( !$pipeline_success_0 ) { $main_exit_code = 1; }
    }

exit $main_exit_code;
