#!/usr/bin/env perl
use strict;
use warnings;
use Carp;
use English qw(-no_match_vars $ERRNO $EVAL_ERROR $INPUT_RECORD_SEPARATOR $OS_ERROR $PROGRAM_NAME);
use locale;
use IPC::Open3;

my $main_exit_code = 0;
my $ls_success     = 0;
my $__set_e        = 0;
my $output         = q{};
our $CHILD_ERROR;

my $MAGIC_129 = 129;

my $test_description;
my @test_description;
my %test_description;
$test_description = "Basic porcelain support for subtrees\n\nThis test verifies the basic operation of the add, merge, split, pull,\nand push subcommands of git subtree.\n";
my $TEST_DIRECTORY;
my @TEST_DIRECTORY;
my %TEST_DIRECTORY;
$TEST_DIRECTORY = do { use Cwd; getcwd(); };
$main_exit_code = system('bash', '/../../../t') >> 8;
$main_exit_code = system('.', "$TEST_DIRECTORY", '/test-lib.sh') >> 8;

sub subtree_test_create_repo {
    if (do {
$main_exit_code = system('test_create_repo', "$_[0]") >> 8;
        $CHILD_ERROR == 0
    }) {
                $main_exit_code = system('git', '-C', "$_[0]", 'config', 'log.date', 'relative') >> 8;
    }
    return;
}
$main_exit_code = system('test_create_commit', q{}, "\n\trepo=$1 &&\n\tcommit=$2 &&\n\tcd \"$repo\" &&\n\tmkdir -p \"$(dirname \"$commit\")\" \t|| error \"Could not create directory for commit\"\n\techo \"$commit\" >\"$commit\" &&\n\tgit add \"$commit\" || error \"Could not add commit\"\n\tgit commit -m \"$commit\" || error \"Could not commit\"\n") >> 8;

sub test_wrong_flag {
    if (do {
if (do {
        do {
        open my $original_stdout, '>&', STDOUT
      or die "Cannot save STDOUT: $OS_ERROR\n";
        open STDOUT, '>', 'out'
      or die "Cannot open file: $OS_ERROR\n";
local *STDERR;
open STDERR, '>', 'err' or croak "Cannot open file: $OS_ERROR\n";
        my $tmp = do {
        $main_exit_code = system('test_must_fail', "@ARGV") >> 8;
        };
        print $tmp;
        open STDOUT, '>&', $original_stdout
      or die "Cannot restore STDOUT: $OS_ERROR\n";
        close $original_stdout
      or die "Close failed: $OS_ERROR\n";
    };
} == 0) {
        $main_exit_code = system('test_must_be_empty', 'out') >> 8;
}
        $CHILD_ERROR == 0
    }) {
        my $grep_result_0;
my @grep_lines_0 = ();
my @grep_filenames_0 = ();
if (-e "err") {
    open my $fh, '<', "err" or croak "Cannot open file: $ERRNO";
    while (my $line = <$fh>) {
        chomp $line;
        push @grep_lines_0, $line;
        push @grep_filenames_0, "err";
    }
    close $fh
        or croak "Close failed: $OS_ERROR";
}
else { print {*STDERR} "grep: err: No such file or directory\n"; }
my @grep_filtered_0 = grep { /flag\ does\ not\ make\ sense\ with/msx } @grep_lines_0;
$grep_result_0 = join "\n", @grep_filtered_0;
        if (!($grep_result_0 =~ m{\n\z}msx || $grep_result_0 eq q{})) {
            $grep_result_0 .= "\n";
        }
print $grep_result_0;
$CHILD_ERROR = scalar @grep_filtered_0 > 0 ? 0 : 1;
    }
    return;
}

sub last_commit_subject {
    $main_exit_code = system('git', 'log', '--pretty=format:%s', '-1') >> 8;
    return;
}

sub test_create_pre2_32_repo {
    if (do {
if (do {
if (do {
if (do {
if (do {
if (do {
if (do {
if (do {
if (do {
if (do {
if (do {
subtree_test_create_repo("$_[0]");
    $CHILD_ERROR == 0
}) {
        subtree_test_create_repo("$_[0]-sub");
}
    $CHILD_ERROR == 0
}) {
        $main_exit_code = system('test_commit', '-C', "$_[0]", 'main1') >> 8;
}
    $CHILD_ERROR == 0
}) {
        $main_exit_code = system('test_commit', '-C', "$_[0]-sub", '--annotate', 'sub1') >> 8;
}
    $CHILD_ERROR == 0
}) {
        $main_exit_code = system('git', '-C', "$_[0]", 'subtree', 'add', '--prefix=sub', '--squash', "../$_[0]-sub", 'sub1') >> 8;
}
    $CHILD_ERROR == 0
}) {
        my $tag;
    my @tag;
    my %tag;
    $tag = do {
    my ($in_1, $out_1);
    my $pid_1 = open3($in_1, $out_1, '>&STDERR', 'git', '-C', "$_[0]", 'rev-parse', 'FETCH_HEAD');
    close $in_1 or croak 'Close failed: $OS_ERROR';
    my $result_1 = do { local $INPUT_RECORD_SEPARATOR = undef; <$out_1> };
    close $out_1 or croak 'Close failed: $OS_ERROR';
    waitpid $pid_1, 0;
    $result_1
};
}
    $CHILD_ERROR == 0
}) {
        my $commit;
    my @commit;
    my %commit;
    $commit = do {
    my ($in_2, $out_2);
    my $pid_2 = open3($in_2, $out_2, '>&STDERR', 'git', '-C', "$_[0]", 'rev-parse', 'FETCH_HEAD^', '\'commit\'');
    close $in_2 or croak 'Close failed: $OS_ERROR';
    my $result_2 = do { local $INPUT_RECORD_SEPARATOR = undef; <$out_2> };
    close $out_2 or croak 'Close failed: $OS_ERROR';
    waitpid $pid_2, 0;
    $result_2
};
}
    $CHILD_ERROR == 0
}) {
        do {
        open my $original_stdout, '>&', STDOUT
      or die "Cannot save STDOUT: $OS_ERROR\n";
        open STDOUT, '>', 'msg'
      or die "Cannot open file: $OS_ERROR\n";
        my $tmp = do {
        $main_exit_code = system('git', '-C', "$_[0]", 'log', '-1', '--format=%B', 'HEAD', '^2') >> 8;
        };
        print $tmp;
        open STDOUT, '>&', $original_stdout
      or die "Cannot restore STDOUT: $OS_ERROR\n";
        close $original_stdout
      or die "Close failed: $OS_ERROR\n";
    };
}
    $CHILD_ERROR == 0
}) {
        $main_exit_code = system('test_commit', '-C', "$_[0]-sub", '--annotate', 'sub2') >> 8;
}
    $CHILD_ERROR == 0
}) {
        $main_exit_code = system('git', 'clone', '--no-local', "$_[0]", "$_[0]-clone") >> 8;
}
    $CHILD_ERROR == 0
}) {
        my $new_commit;
    my @new_commit;
    my %new_commit;
    $new_commit = do { local $CHILD_ERROR = 0; my $_pipeline_result = do {
        my $output_3 = q{};
        my $output_printed_3;
        my $pipeline_success_3 = 1;
        $output_3 = do { my $cat_chunk = q{}; if ( open my $fh, '<', 'msg' ) { local $INPUT_RECORD_SEPARATOR = undef; $cat_chunk = <$fh>; close $fh; } else { carp 'cat: ' . 'msg' . ': ' . $OS_ERROR . "\n"; } $cat_chunk; };
        if ($CHILD_ERROR != 0) { $pipeline_success_3 = 0; }
        my @sed_lines_3 = split /\n/msx, $output_3;
        my @sed_result_3;
        foreach my $line (@sed_lines_3) {
        chomp $line;
        push @sed_result_3, $line;
        }
        $output_3 = join "\n", @sed_result_3;


        my $cmd_5 = 'git';
        my ($in_4, $out_4);
        my $pid_4 = open3($in_4, $out_4, '>&STDERR', $cmd_5, '-C', 'commit-tree', 'HEAD', '^2^');
        print {$in_4} $output_3;
        close $in_4 or croak 'Close failed: $OS_ERROR';
        $output_3 = do { local $INPUT_RECORD_SEPARATOR = undef; <$out_4> };
        close $out_4 or croak 'Close failed: $OS_ERROR';
        waitpid $pid_4, 0;
        if ( !$pipeline_success_3 ) { $main_exit_code = 1; }
        $output_3 =~ s/\n+\z//msx;
        $output_3;
}; $_pipeline_result; };
}
        $CHILD_ERROR == 0
    }) {
                $main_exit_code = system('git', '-C', "$_[0]-clone", 'replace', 'HEAD', '^2', $new_commit) >> 8;
    }
    return;
}
$main_exit_code = system('test_expect_success', 'shows short help text for -h', "\n\ttest_expect_code 129 git subtree -h >out 2>err &&\n\ttest_must_be_empty err &&\n\tgrep -e \"^ *or: git subtree pull\" out &&\n\tgrep -F -e \"--[no-]annotate\" out\n") >> 8;
$main_exit_code = system('test_expect_success', 'no merge from non-existent subtree', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\ttest_must_fail git subtree merge --prefix=\"sub dir\" FETCH_HEAD\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'no pull from non-existent subtree', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\ttest_must_fail git subtree pull --prefix=\"sub dir\" ./\"sub proj\" HEAD\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'add rejects flags for split', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\ttest_wrong_flag git subtree add --prefix=\"sub dir\" --annotate=foo FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree add --prefix=\"sub dir\" --branch=foo FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree add --prefix=\"sub dir\" --ignore-joins FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree add --prefix=\"sub dir\" --onto=foo FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree add --prefix=\"sub dir\" --rejoin FETCH_HEAD\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'add subproj as subtree into sub dir/ with --prefix', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD &&\n\t\ttest \"$(last_commit_subject)\" = \"Add ", "\\'", 'sub dir/', "\\'", ' from commit ', "\\'", '$(git rev-parse FETCH_HEAD)', "\\'", "\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'add subproj as subtree into sub dir/ with --prefix and --message', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" --message=\"Added subproject\" FETCH_HEAD &&\n\t\ttest \"$(last_commit_subject)\" = \"Added subproject\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'add subproj as subtree into sub dir/ with --prefix as -P and --message as -m', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add -P \"sub dir\" -m \"Added subproject\" FETCH_HEAD &&\n\t\ttest \"$(last_commit_subject)\" = \"Added subproject\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'add subproj as subtree into sub dir/ with --squash and --prefix and --message', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" --message=\"Added subproject with squash\" --squash FETCH_HEAD &&\n\t\ttest \"$(last_commit_subject)\" = \"Added subproject with squash\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'merge rejects flags for split', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\ttest_wrong_flag git subtree merge --prefix=\"sub dir\" --annotate=foo FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree merge --prefix=\"sub dir\" --branch=foo FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree merge --prefix=\"sub dir\" --ignore-joins FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree merge --prefix=\"sub dir\" --onto=foo FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree merge --prefix=\"sub dir\" --rejoin FETCH_HEAD\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'merge new subproj history into sub dir/ with --prefix', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\ttest \"$(last_commit_subject)\" = \"Merge commit ", "\\'", '$(git rev-parse FETCH_HEAD)', "\\'", "\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'merge new subproj history into sub dir/ with --prefix and --message', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" --message=\"Merged changes from subproject\" FETCH_HEAD &&\n\t\ttest \"$(last_commit_subject)\" = \"Merged changes from subproject\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'merge new subproj history into sub dir/ with --squash and --prefix and --message', "\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\tsubtree_test_create_repo \"$test_count\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" --message=\"Merged changes from subproject using squash\" --squash FETCH_HEAD &&\n\t\ttest \"$(last_commit_subject)\" = \"Merged changes from subproject using squash\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'merge the added subproj again, should do nothing', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD &&\n\t\t# this shouldn not actually do anything, since FETCH_HEAD\n\t\t# is already a parent\n\t\tresult=$(git merge -s ours -m \"merge -s -ours\" FETCH_HEAD) &&\n\t\ttest \"${result}\" = \"Already up to date.\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'merge new subproj history into subdir/ with a slash appended to the argument of --prefix', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/subproj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/subproj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./subproj HEAD &&\n\t\tgit subtree add --prefix=subdir/ FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/subproj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./subproj HEAD &&\n\t\tgit subtree merge --prefix=subdir/ FETCH_HEAD &&\n\t\ttest \"$(last_commit_subject)\" = \"Merge commit ", "\\'", '$(git rev-parse FETCH_HEAD)', "\\'", "\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'merge with --squash after annotated tag was added/merged with --squash pre-v2.32.0 ', "\n\ttest_create_pre2_32_repo \"$test_count\" &&\n\tgit -C \"$test_count-clone\" fetch \"../$test_count-sub\" sub2  &&\n\ttest_must_fail git -C \"$test_count-clone\" subtree merge --prefix=\"sub\" --squash FETCH_HEAD &&\n\tgit -C \"$test_count-clone\" subtree merge --prefix=\"sub\" --squash FETCH_HEAD  \"../$test_count-sub\"\n") >> 8;
$main_exit_code = system('test_expect_success', 'split requires option --prefix', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD &&\n\t\techo \"fatal: you must provide the --prefix option.\" >expected &&\n\t\ttest_must_fail git subtree split >actual 2>&1 &&\n\t\ttest_debug \"printf ", "expected: ", "\" &&\n\t\ttest_debug \"cat expected\" &&\n\t\ttest_debug \"printf ", "actual: ", "\" &&\n\t\ttest_debug \"cat actual\" &&\n\t\ttest_cmp expected actual\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'split requires path given by option --prefix must exist', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD &&\n\t\techo \"fatal: ", "\\'", 'non-existent-directory', "\\'", ' does not exist; use ', "\\'", 'git subtree add', "\\'", "\" >expected &&\n\t\ttest_must_fail git subtree split --prefix=non-existent-directory >actual 2>&1 &&\n\t\ttest_debug \"printf ", "expected: ", "\" &&\n\t\ttest_debug \"cat expected\" &&\n\t\ttest_debug \"printf ", "actual: ", "\" &&\n\t\ttest_debug \"cat actual\" &&\n\t\ttest_cmp expected actual\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'split rejects flags for add', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\ttest_wrong_flag git subtree split --prefix=\"sub dir\" --squash &&\n\t\ttest_wrong_flag git subtree split --prefix=\"sub dir\" --message=foo\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'split sub dir/ with --rejoin', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --rejoin &&\n\t\ttest \"$(last_commit_subject)\" = \"Split ", "\\'", 'sub dir/', "\\'", ' into commit ', "\\'", '$split_hash', "\\'", "\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'split sub dir/ with --rejoin from scratch', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tmkdir \"sub dir\" &&\n\t\techo file >\"sub dir\"/file &&\n\t\tgit add \"sub dir/file\" &&\n\t\tgit commit -m\"sub dir file\" &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --rejoin) &&\n\t\tgit subtree split --prefix=\"sub dir\" --rejoin &&\n\t\ttest \"$(last_commit_subject)\" = \"Split ", "\\'", 'sub dir/', "\\'", ' into commit ', "\\'", '$split_hash', "\\'", "\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'split sub dir/ with --rejoin and --message', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tgit subtree split --prefix=\"sub dir\" --message=\"Split & rejoin\" --annotate=\"*\" --rejoin &&\n\t\ttest \"$(last_commit_subject)\" = \"Split & rejoin\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "split \"sub dir\"/ with --rejoin and --squash", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" --squash FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree pull --prefix=\"sub dir\" --squash ./\"sub proj\" HEAD &&\n\t\tMAIN=$(git rev-parse --verify HEAD) &&\n\t\tSUB=$(git -C \"sub proj\" rev-parse --verify HEAD) &&\n\n\t\tSPLIT=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\" --rejoin --squash) &&\n\n\t\ttest_must_fail git merge-base --is-ancestor $SUB HEAD &&\n\t\ttest_must_fail git merge-base --is-ancestor $SPLIT HEAD &&\n\t\tgit rev-list HEAD ^$MAIN >commit-list &&\n\t\ttest_line_count = 2 commit-list &&\n\t\ttest \"$(git rev-parse --verify HEAD:)\"           = \"$(git rev-parse --verify $MAIN:)\" &&\n\t\ttest \"$(git rev-parse --verify HEAD:\"sub dir\")\"  = \"$(git rev-parse --verify $SPLIT:)\" &&\n\t\ttest \"$(git rev-parse --verify HEAD^1)\"          = $MAIN &&\n\t\ttest \"$(git rev-parse --verify HEAD^2)\"         != $SPLIT &&\n\t\ttest \"$(git rev-parse --verify HEAD^2:)\"         = \"$(git rev-parse --verify $SPLIT:)\" &&\n\t\ttest \"$(last_commit_subject)\" = \"Split ", "\\'", 'sub dir/', "\\'", ' into commit ', "\\'", '$SPLIT', "\\'", "\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "split then pull \"sub dir\"/ with --rejoin and --squash", "\n\t# 1. \"add\"\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\tgit -C \"$test_count\" subtree --prefix=\"sub dir\" add --squash ./\"sub proj\" HEAD &&\n\n\t# 2. commit from parent\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\n\t# 3. \"split --rejoin --squash\"\n\tgit -C \"$test_count\" subtree --prefix=\"sub dir\" split --rejoin --squash &&\n\n\t# 4. \"pull --squash\"\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\tgit -C \"$test_count\" subtree -d --prefix=\"sub dir\" pull --squash ./\"sub proj\" HEAD &&\n\n\ttest_must_fail git merge-base HEAD FETCH_HEAD\n") >> 8;
$main_exit_code = system('test_expect_success', "split \"sub dir\"/ with --branch", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br &&\n\t\ttest \"$(git rev-parse subproj-br)\" = \"$split_hash\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'check hash of split', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br &&\n\t\ttest \"$(git rev-parse subproj-br)\" = \"$split_hash\" &&\n\t\t# Check hash of split\n\t\tnew_hash=$(git rev-parse subproj-br^2) &&\n\t\t(\n\t\t\tcd ./\"sub proj\" &&\n\t\t\tsubdir_hash=$(git rev-parse HEAD) &&\n\t\t\ttest \"$new_hash\" = \"$subdir_hash\"\n\t\t)\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "split \"sub dir\"/ with --branch for an existing branch", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit branch subproj-br FETCH_HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br &&\n\t\ttest \"$(git rev-parse subproj-br)\" = \"$split_hash\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "split \"sub dir\"/ with --branch for an incompatible branch", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit branch init HEAD &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\ttest_must_fail git subtree split --prefix=\"sub dir\" --branch init\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'split after annotated tag was added/merged with --squash pre-v2.32.0', "\n\ttest_create_pre2_32_repo \"$test_count\" &&\n\ttest_must_fail git -C \"$test_count-clone\" subtree split --prefix=\"sub\" HEAD &&\n\tgit -C \"$test_count-clone\" subtree split --prefix=\"sub\" HEAD \"../$test_count-sub\"\n") >> 8;
$main_exit_code = system('test_expect_success', 'pull requires option --prefix', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\ttest_must_fail git subtree pull ./\"sub proj\" HEAD >out 2>err &&\n\n\t\techo \"fatal: you must provide the --prefix option.\" >expected &&\n\t\ttest_must_be_empty out &&\n\t\ttest_cmp expected err\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'pull requires path given by option --prefix must exist', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\ttest_must_fail git subtree pull --prefix=\"sub dir\" ./\"sub proj\" HEAD >out 2>err &&\n\n\t\techo \"fatal: ", "\\'", 'sub dir', "\\'", ' does not exist; use ', "\\'", 'git subtree add', "\\'", "\" >expected &&\n\t\ttest_must_be_empty out &&\n\t\ttest_cmp expected err\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'pull basic operation', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\texp=$(git -C \"sub proj\" rev-parse --verify HEAD:) &&\n\t\tgit subtree pull --prefix=\"sub dir\" ./\"sub proj\" HEAD &&\n\t\tact=$(git rev-parse --verify HEAD:\"sub dir\") &&\n\t\ttest \"$act\" = \"$exp\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'pull rejects flags for split', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\ttest_must_fail git subtree pull --prefix=\"sub dir\" --annotate=foo ./\"sub proj\" HEAD &&\n\t\ttest_must_fail git subtree pull --prefix=\"sub dir\" --branch=foo ./\"sub proj\" HEAD &&\n\t\ttest_must_fail git subtree pull --prefix=\"sub dir\" --ignore-joins ./\"sub proj\" HEAD &&\n\t\ttest_must_fail git subtree pull --prefix=\"sub dir\" --onto=foo ./\"sub proj\" HEAD &&\n\t\ttest_must_fail git subtree pull --prefix=\"sub dir\" --rejoin ./\"sub proj\" HEAD\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'pull with --squash after annotated tag was added/merged with --squash pre-v2.32.0 ', "\n\ttest_create_pre2_32_repo \"$test_count\" &&\n\tgit -C \"$test_count-clone\" subtree -d pull --prefix=\"sub\" --squash \"../$test_count-sub\" sub2\n") >> 8;
$main_exit_code = system('test_expect_success', 'push requires option --prefix', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD &&\n\t\techo \"fatal: you must provide the --prefix option.\" >expected &&\n\t\ttest_must_fail git subtree push \"./sub proj\" from-mainline >actual 2>&1 &&\n\t\ttest_debug \"printf ", "expected: ", "\" &&\n\t\ttest_debug \"cat expected\" &&\n\t\ttest_debug \"printf ", "actual: ", "\" &&\n\t\ttest_debug \"cat actual\" &&\n\t\ttest_cmp expected actual\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'push requires path given by option --prefix must exist', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD &&\n\t\techo \"fatal: ", "\\'", 'non-existent-directory', "\\'", ' does not exist; use ', "\\'", 'git subtree add', "\\'", "\" >expected &&\n\t\ttest_must_fail git subtree push --prefix=non-existent-directory \"./sub proj\" from-mainline >actual 2>&1 &&\n\t\ttest_debug \"printf ", "expected: ", "\" &&\n\t\ttest_debug \"cat expected\" &&\n\t\ttest_debug \"printf ", "actual: ", "\" &&\n\t\ttest_debug \"cat actual\" &&\n\t\ttest_cmp expected actual\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'push rejects flags for add', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\ttest_wrong_flag git subtree split --prefix=\"sub dir\" --squash ./\"sub proj\" from-mainline &&\n\t\ttest_wrong_flag git subtree split --prefix=\"sub dir\" --message=foo ./\"sub proj\" from-mainline\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'push basic operation', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tbefore=$(git rev-parse --verify HEAD) &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\") &&\n\t\tgit subtree push --prefix=\"sub dir\" ./\"sub proj\" from-mainline &&\n\t\ttest \"$before\" = \"$(git rev-parse --verify HEAD)\" &&\n\t\ttest \"$split_hash\" = \"$(git -C \"sub proj\" rev-parse --verify refs/heads/from-mainline)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'push sub dir/ with --rejoin', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree push --prefix=\"sub dir\" --annotate=\"*\" --rejoin ./\"sub proj\" from-mainline &&\n\t\ttest \"$(last_commit_subject)\" = \"Split ", "\\'", 'sub dir/', "\\'", ' into commit ', "\\'", '$split_hash', "\\'", "\" &&\n\t\ttest \"$split_hash\" = \"$(git -C \"sub proj\" rev-parse --verify refs/heads/from-mainline)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'push sub dir/ with --rejoin from scratch', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tmkdir \"sub dir\" &&\n\t\techo file >\"sub dir\"/file &&\n\t\tgit add \"sub dir/file\" &&\n\t\tgit commit -m\"sub dir file\" &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --rejoin) &&\n\t\tgit init --bare \"sub proj.git\" &&\n\t\tgit subtree push --prefix=\"sub dir\" --rejoin ./\"sub proj.git\" from-mainline &&\n\t\ttest \"$(last_commit_subject)\" = \"Split ", "\\'", 'sub dir/', "\\'", ' into commit ', "\\'", '$split_hash', "\\'", "\" &&\n\t\ttest \"$split_hash\" = \"$(git -C \"sub proj.git\" rev-parse --verify refs/heads/from-mainline)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'push sub dir/ with --rejoin and --message', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tgit subtree push --prefix=\"sub dir\" --message=\"Split & rejoin\" --annotate=\"*\" --rejoin ./\"sub proj\" from-mainline &&\n\t\ttest \"$(last_commit_subject)\" = \"Split & rejoin\" &&\n\t\tsplit_hash=\"$(git rev-parse --verify HEAD^2)\" &&\n\t\ttest \"$split_hash\" = \"$(git -C \"sub proj\" rev-parse --verify refs/heads/from-mainline)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "push \"sub dir\"/ with --rejoin and --squash", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" --squash FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree pull --prefix=\"sub dir\" --squash ./\"sub proj\" HEAD &&\n\t\tMAIN=$(git rev-parse --verify HEAD) &&\n\t\tSUB=$(git -C \"sub proj\" rev-parse --verify HEAD) &&\n\n\t\tSPLIT=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree push --prefix=\"sub dir\" --annotate=\"*\" --rejoin --squash ./\"sub proj\" from-mainline &&\n\n\t\ttest_must_fail git merge-base --is-ancestor $SUB HEAD &&\n\t\ttest_must_fail git merge-base --is-ancestor $SPLIT HEAD &&\n\t\tgit rev-list HEAD ^$MAIN >commit-list &&\n\t\ttest_line_count = 2 commit-list &&\n\t\ttest \"$(git rev-parse --verify HEAD:)\"           = \"$(git rev-parse --verify $MAIN:)\" &&\n\t\ttest \"$(git rev-parse --verify HEAD:\"sub dir\")\"  = \"$(git rev-parse --verify $SPLIT:)\" &&\n\t\ttest \"$(git rev-parse --verify HEAD^1)\"          = $MAIN &&\n\t\ttest \"$(git rev-parse --verify HEAD^2)\"         != $SPLIT &&\n\t\ttest \"$(git rev-parse --verify HEAD^2:)\"         = \"$(git rev-parse --verify $SPLIT:)\" &&\n\t\ttest \"$(last_commit_subject)\" = \"Split ", "\\'", 'sub dir/', "\\'", ' into commit ', "\\'", '$SPLIT', "\\'", "\" &&\n\t\ttest \"$SPLIT\" = \"$(git -C \"sub proj\" rev-parse --verify refs/heads/from-mainline)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "push \"sub dir\"/ with --branch", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree push --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br ./\"sub proj\" from-mainline &&\n\t\ttest \"$(git rev-parse subproj-br)\" = \"$split_hash\" &&\n\t\ttest \"$split_hash\" = \"$(git -C \"sub proj\" rev-parse --verify refs/heads/from-mainline)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'check hash of push', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree push --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br ./\"sub proj\" from-mainline &&\n\t\ttest \"$(git rev-parse subproj-br)\" = \"$split_hash\" &&\n\t\t# Check hash of split\n\t\tnew_hash=$(git rev-parse subproj-br^2) &&\n\t\t(\n\t\t\tcd ./\"sub proj\" &&\n\t\t\tsubdir_hash=$(git rev-parse HEAD) &&\n\t\t\ttest \"$new_hash\" = \"$subdir_hash\"\n\t\t) &&\n\t\ttest \"$split_hash\" = \"$(git -C \"sub proj\" rev-parse --verify refs/heads/from-mainline)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "push \"sub dir\"/ with --branch for an existing branch", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit branch subproj-br FETCH_HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tsplit_hash=$(git subtree split --prefix=\"sub dir\" --annotate=\"*\") &&\n\t\tgit subtree push --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br ./\"sub proj\" from-mainline &&\n\t\ttest \"$(git rev-parse subproj-br)\" = \"$split_hash\" &&\n\t\ttest \"$split_hash\" = \"$(git -C \"sub proj\" rev-parse --verify refs/heads/from-mainline)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "push \"sub dir\"/ with --branch for an incompatible branch", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit branch init HEAD &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\ttest_must_fail git subtree push --prefix=\"sub dir\" --branch init \"./sub proj\" from-mainline\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "push \"sub dir\"/ with a local rev", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tbad_tree=$(git rev-parse --verify HEAD:\"sub dir\") &&\n\t\tgood_tree=$(git rev-parse --verify HEAD^:\"sub dir\") &&\n\t\tgit subtree push --prefix=\"sub dir\" --annotate=\"*\" ./\"sub proj\" HEAD^:from-mainline &&\n\t\tsplit_tree=$(git -C \"sub proj\" rev-parse --verify refs/heads/from-mainline:) &&\n\t\ttest \"$split_tree\" = \"$good_tree\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'push after annotated tag was added/merged with --squash pre-v2.32.0', "\n\ttest_create_pre2_32_repo \"$test_count\" &&\n\ttest_create_commit \"$test_count-clone\" sub/main-sub1 &&\n\tgit -C \"$test_count-clone\" subtree push --prefix=\"sub\" \"../$test_count-sub\" from-mainline\n") >> 8;
$main_exit_code = system('test_expect_success', 'make sure exactly the right set of files ends up in the subproj', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub3 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub3 &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD &&\n\n\t\ttest_write_lines main-sub1 main-sub2 main-sub3 main-sub4 \\\n\t\t\tsub1 sub2 sub3 sub4 >expect &&\n\t\tgit ls-files >actual &&\n\t\ttest_cmp expect actual\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "make sure the subproj *only* contains commits that affect the \"sub dir\"", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub3 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub3 &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD &&\n\n\t\ttest_write_lines main-sub1 main-sub2 main-sub3 main-sub4 \\\n\t\t\tsub1 sub2 sub3 sub4 >expect &&\n\t\tgit log --name-only --pretty=format:\"\" >log &&\n\t\tsort <log | sed \"/^\\$/ d\" >actual &&\n\t\ttest_cmp expect actual\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'make sure exactly the right set of files ends up in the mainline', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub3 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub3 &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree pull --prefix=\"sub dir\" ./\"sub proj\" HEAD &&\n\n\t\ttest_write_lines main1 main2 >chkm &&\n\t\ttest_write_lines main-sub1 main-sub2 main-sub3 main-sub4 >chkms &&\n\t\tsed \"s,^,sub dir/,\" chkms >chkms_sub &&\n\t\ttest_write_lines sub1 sub2 sub3 sub4 >chks &&\n\t\tsed \"s,^,sub dir/,\" chks >chks_sub &&\n\n\t\tcat chkm chkms_sub chks_sub >expect &&\n\t\tgit ls-files >actual &&\n\t\ttest_cmp expect actual\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'make sure each filename changed exactly once in the entire history', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit config log.date relative &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub3 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub3 &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree pull --prefix=\"sub dir\" ./\"sub proj\" HEAD &&\n\n\t\ttest_write_lines main1 main2 >chkm &&\n\t\ttest_write_lines sub1 sub2 sub3 sub4 >chks &&\n\t\ttest_write_lines main-sub1 main-sub2 main-sub3 main-sub4 >chkms &&\n\t\tsed \"s,^,sub dir/,\" chkms >chkms_sub &&\n\n\t\t# main-sub?? and /\"sub dir\"/main-sub?? both change, because those are the\n\t\t# changes that were split into their own history.  And \"sub dir\"/sub?? never\n\t\t# change, since they were *only* changed in the subtree branch.\n\t\tgit log --name-only --pretty=format:\"\" >log &&\n\t\tsort <log >sorted-log &&\n\t\tsed \"/^$/ d\" sorted-log >actual &&\n\n\t\tcat chkms chkm chks chkms_sub >expect-unsorted &&\n\t\tsort expect-unsorted >expect &&\n\t\ttest_cmp expect actual\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'make sure the --rejoin commits never make it into subproj', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub3 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub3 &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree pull --prefix=\"sub dir\" ./\"sub proj\" HEAD &&\n\t\ttest \"$(git log --pretty=format:\"%s\" HEAD^2 | grep -i split)\" = \"\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "make sure no \"git subtree\" tagged commits make it into subproj", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub3 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub3 &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\t git merge FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub4 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --annotate=\"*\" --branch subproj-br --rejoin\n\t) &&\n\t(\n\t\tcd \"$test_count/sub proj\" &&\n\t\tgit fetch .. subproj-br &&\n\t\tgit merge FETCH_HEAD\n\t) &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree pull --prefix=\"sub dir\" ./\"sub proj\" HEAD &&\n\n\t\t# They are meaningless to subproj since one side of the merge refers to the mainline\n\t\ttest \"$(git log --pretty=format:\"%s%n%b\" HEAD^2 | grep \"git-subtree.*:\")\" = \"\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', "make sure \"git subtree split\" find the correct parent", "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit branch subproj-ref FETCH_HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --branch subproj-br &&\n\n\t\t# at this point, the new commit parent should be subproj-ref, if it is\n\t\t# not, something went wrong (the \"newparent\" of \"HEAD~\" commit should\n\t\t# have been sub2, but it was not, because its cache was not set to\n\t\t# itself)\n\t\ttest \"$(git log --pretty=format:%P -1 subproj-br)\" = \"$(git rev-parse subproj-ref)\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'split a new subtree without --onto option', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --branch subproj-br\n\t) &&\n\tmkdir \"$test_count\"/\"sub dir2\" &&\n\ttest_create_commit \"$test_count\" \"sub dir2\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\n\t\t# also test that we still can split out an entirely new subtree\n\t\t# if the parent of the first commit in the tree is not empty,\n\t\t# then the new subtree has accidentally been attached to something\n\t\tgit subtree split --prefix=\"sub dir2\" --branch subproj2-br &&\n\t\ttest \"$(git log --pretty=format:%P -1 subproj2-br)\" = \"\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'verify one file change per commit', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit branch sub1 FETCH_HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" sub1\n\t) &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir\" --branch subproj-br\n\t) &&\n\tmkdir \"$test_count\"/\"sub dir2\" &&\n\ttest_create_commit \"$test_count\" \"sub dir2\"/main-sub2 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree split --prefix=\"sub dir2\" --branch subproj2-br &&\n\n\t\tgit log --format=\"%H\" >commit-list &&\n\t\twhile read commit\n\t\tdo\n\t\t\tgit log -n1 --format=\"\" --name-only \"$commit\" >file-list &&\n\t\t\ttest_line_count -le 1 file-list || return 1\n\t\tdone <commit-list\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'push split to subproj', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tsubtree_test_create_repo \"$test_count/sub proj\" &&\n\ttest_create_commit \"$test_count\" main1 &&\n\ttest_create_commit \"$test_count/sub proj\" sub1 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree add --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub1 &&\n\ttest_create_commit \"$test_count\" main2 &&\n\ttest_create_commit \"$test_count/sub proj\" sub2 &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub2 &&\n\t(\n\t\tcd $test_count/\"sub proj\" &&\n\t\tgit branch sub-branch-1 &&\n\t\tcd .. &&\n\t\tgit fetch ./\"sub proj\" HEAD &&\n\t\tgit subtree merge --prefix=\"sub dir\" FETCH_HEAD\n\t) &&\n\ttest_create_commit \"$test_count\" \"sub dir\"/main-sub3 &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit subtree push ./\"sub proj\" --prefix \"sub dir\" sub-branch-1 &&\n\t\tcd ./\"sub proj\" &&\n\t\tgit checkout sub-branch-1 &&\n\t\ttest \"$(last_commit_subject)\" = \"sub dir/main-sub3\"\n\t)\n") >> 8;
$main_exit_code = system('test_expect_success', 'subtree descendant check', "\n\tsubtree_test_create_repo \"$test_count\" &&\n\tdefaultBranch=$(sed \"s,ref: refs/heads/,,\" \"$test_count/.git/HEAD\") &&\n\ttest_create_commit \"$test_count\" folder_subtree/a &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit branch branch\n\t) &&\n\ttest_create_commit \"$test_count\" folder_subtree/0 &&\n\ttest_create_commit \"$test_count\" folder_subtree/b &&\n\tcherry=$(cd \"$test_count\" && git rev-parse HEAD) &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit checkout branch\n\t) &&\n\ttest_create_commit \"$test_count\" commit_on_branch &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit cherry-pick $cherry &&\n\t\tgit checkout $defaultBranch &&\n\t\tgit merge -m \"merge should be kept on subtree\" branch &&\n\t\tgit branch no_subtree_work_branch\n\t) &&\n\ttest_create_commit \"$test_count\" folder_subtree/d &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit checkout no_subtree_work_branch\n\t) &&\n\ttest_create_commit \"$test_count\" not_a_subtree_change &&\n\t(\n\t\tcd \"$test_count\" &&\n\t\tgit checkout $defaultBranch &&\n\t\tgit merge -m \"merge should be skipped on subtree\" no_subtree_work_branch &&\n\n\t\tgit subtree split --prefix folder_subtree/ --branch subtree_tip $defaultBranch &&\n\t\tgit subtree split --prefix folder_subtree/ --branch subtree_branch branch &&\n\t\ttest $(git rev-list --count subtree_tip..subtree_branch) = 0\n\t)\n") >> 8;
$main_exit_code = system('bash', 'test_done') >> 8;

exit $main_exit_code;
