#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/dkms 3.0.3-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/kernel_install.d_dkms 3.0.3-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/rules 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/prerm 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/postinst 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/dirs 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/copyright 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/control 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/compat 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/changelog 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/debian/README.Debian 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkdeb/Makefile 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkbmdeb/debian/rules 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkbmdeb/debian/copyright 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkbmdeb/debian/control 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkbmdeb/debian/compat 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkbmdeb/debian/changelog 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkbmdeb/debian/README.Debian 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/template-dkms-mkbmdeb/Makefile 3.0.3-3\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dkms/sign_helper.sh 3.0.10-8\~ -- "$@"
# End automatically added section
