#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/dnsmasq dnsmasq-base 2.84-1.2\~ dnsmasq -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/dnsmasq" ] ; then
	chmod +x "/etc/init.d/dnsmasq" >/dev/null || true
fi
# End automatically added section
