#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "remove" ] && [ -x "/etc/init.d/docker" ] ; then
	chmod -x "/etc/init.d/docker" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d docker remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper rm_conffile /etc/init/docker.conf 5:24.0.5-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'docker.service' 'docker.socket' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_apparmor/4.0.1really4.0.0-beta3-0ubuntu0.1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/docker-ce" ] ; then
    rm -f "/etc/apparmor.d/disable/docker-ce" || true
    rm -f "/etc/apparmor.d/force-complain/docker-ce" || true
    rm -f "/etc/apparmor.d/local/docker-ce" || true
    rm -f /var/cache/apparmor/*/"docker-ce" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section
