#!/bin/sh
set -e

case "${1:-}" in
  purge)
    rm -f /etc/fake-hwclock.data
    ;;

  *) :;;
esac

# Automatically added by dh_installinit/13.11.8ubuntu1
if [ "$1" = "remove" ] && [ -x "/etc/init.d/fake-hwclock" ] ; then
	chmod -x "/etc/init.d/fake-hwclock" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d fake-hwclock remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.8ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.8ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fake-hwclock-save.service' 'fake-hwclock-save.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.8ubuntu1
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.8ubuntu1
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'fake-hwclock-load.service' >/dev/null || true
	fi
fi
# End automatically added section

