#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.11.8ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'fake-hwclock-save.service' 'fake-hwclock-save.timer' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.11.8ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'fake-hwclock-load.service' >/dev/null || true
fi
# End automatically added section
