#!/bin/sh
set -e

# Remove Python bytecode as needed
py3clean -p lirc


# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'lircd.service' 'lircd.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/lircmd" ] ; then
	invoke-rc.d --skip-systemd-native lircmd stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/lircd" ] ; then
	invoke-rc.d --skip-systemd-native lircd stop || exit 1
fi
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p lirc:arm64 
else
	dpkg -L lirc:arm64 | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section

