#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "remove" ] && [ -x "/etc/init.d/lm-sensors" ] ; then
	chmod -x "/etc/init.d/lm-sensors" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d lm-sensors remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper rm_conffile /etc/blacklist.d/lm-sensors 1:2.9.0-14\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/modutils/i2c 1:3.0.1-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/modprobe.d/i2c 1:3.1.0-1\~ -- "$@"
dpkg-maintscript-helper mv_conffile /etc/modprobe.d/lm-sensors /etc/modprobe.d/lm-sensors.conf 1:3.1.0-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/fancontrol 1:3.1.1-5\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'lm-sensors.service' >/dev/null || true
	fi
fi
# End automatically added section
