#!/bin/sh

set -e

case "$1" in
    configure)
        ucf --three-way /usr/share/nfs-common/conffiles/idmapd.conf /etc/idmapd.conf
        ucf --three-way /usr/share/nfs-common/conffiles/nfs-common.default /etc/default/nfs-common
        ucf --three-way /usr/share/nfs-common/conffiles/nfs.conf /etc/nfs.conf

        if ! getent passwd statd >/dev/null; then
            adduser --system --home /var/lib/nfs --no-create-home statd
        fi

        chown statd: /var/lib/nfs/sm \
            /var/lib/nfs/sm.bak
        if [ -f /var/lib/nfs/state ]; then
            chown statd /var/lib/nfs/state
        fi
    ;;
esac

# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/nfs-common" ]; then
		update-rc.d nfs-common defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native nfs-common $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'nfs-client.target' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'nfs-client.target'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'nfs-client.target' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'nfs-client.target' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'auth-rpcgss-module.service' 'nfs-client.target' 'nfs-idmapd.service' 'nfs-utils.service' 'proc-fs-nfsd.mount' 'rpc-gssd.service' 'rpc-statd-notify.service' 'rpc-statd.service' 'rpc-svcgssd.service' >/dev/null || true
	fi
fi
# End automatically added section

