#!/bin/sh
# Copyright 2001 Alberto Gonzalez Iniesta <agi@agi.as>
# Licensed under the GNU General Public License, version 2.  See the file
# /usr/share/common-licenses/GPL or <http://www.gnu.org/copyleft/gpl.txt>.
#
set -e
test $DEBIAN_SCRIPT_DEBUG && set -v -x

# use debconf
. /usr/share/debconf/confmodule

#
# POSIX-compliant shell function
# to check for the existence of a command
# Return 0 if found
#
pathfind() {
    OLDIFS="$IFS"
    IFS=:
    for p in $PATH; do
        if [ -x "$p/$*" ]; then
            IFS="$OLDIFS"
            return 0
        fi
    done
    IFS="$OLDIFS"
    return 1
}


case "$1" in
  configure)
    db_get openvpn/create_tun || RET="false"
    if [ "$RET" = "true" ]; then
      [ -e /dev/net ] || mkdir -m 755 /dev/net
      [ -d /dev/net -a ! -e /dev/net/tun ] && mknod /dev/net/tun c 10 200
    fi
    for f in /run/sendsigs.omit.d/openvpn.*.pid; do
      [ -e "$f" ] && continue
      b="$(basename $f|sed 's/openvpn\.//')"
      # make sure is a vpn name, not *.pid (#730679)
      echo "$b" | grep -q '\*' && continue
      ln -sf "/run/openvpn/$b" "/run/sendsigs.omit.d/openvpn.$b"
    done
    if pidof -c /usr/sbin/openvpn >/dev/null; then
        echo "A reboot is required to replace the running openvpn." >&2
        echo "Please reboot the system as soon as possible." >&2
    fi
  ;;
esac

db_stop

# Automatically added by dh_installtmpfiles/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create openvpn.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/openvpn.conf 2.4.3-3\~ openvpn -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/openvpn" ]; then
		update-rc.d openvpn defaults 16 80 >/dev/null || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	deb-systemd-helper unmask 'openvpn.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'openvpn.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'openvpn.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'openvpn.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'openvpn.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
# vim:set ai et sts=2 sw=2 tw=0:
