#!/bin/sh

set -e

if [ "$1" = purge ] ; then
	rm -rf /run/rpcbind /run/rpcbind.lock /run/rpcbind.sock
fi

# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "remove" ] && [ -x "/etc/init.d/rpcbind" ] ; then
	chmod -x "/etc/init.d/rpcbind" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d rpcbind remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rpcbind.service' 'rpcbind.socket' >/dev/null || true
	fi
fi
# End automatically added section

