#!/bin/sh
set -e

case "$1" in
  purge)
    if [ -d /var/lib/smartmontools ] ; then
      rm -rf  /var/lib/smartmontools
    fi
  ;;

esac

# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "remove" ] && [ -x "/etc/init.d/smartmontools" ] ; then
	chmod -x "/etc/init.d/smartmontools" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d smartmontools remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper rm_conffile /etc/smartd_warning.sh 6.3\+svn4002-2\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/smartd 6.1\+svn3812-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/smartmontools/run.d/10powersave-notify 7.0\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'smartd.service' 'smartmontools.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
