#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    rmdir -p /usr/local/share/zsh/site-functions || true
fi

# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/zsh zsh-common 5.0.7-3 -- "$@"
# End automatically added section
# Automatically added by dh_installmenu/13.14.1ubuntu5
if [ -x "`command -v update-menus`" ] && [ -x "$DPKG_ROOT`command -v update-menus`" ]; then update-menus ; fi
# End automatically added section

