#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper symlink_to_dir /usr/share/doc/zsh zsh-common 5.0.7-3 -- "$@"
# End automatically added section
# Automatically added by dh_usrlocal/13.14.1ubuntu5
(
	while read dir; do
		rmdir "$dir" 2>/dev/null || true
	done
) << DATA
/usr/local/share/zsh/site-functions
/usr/local/share/zsh
DATA
# End automatically added section
