// @generated by build.rs — do not edit. (scratch copy for compilation)
// Stmt nodes from src/shir_nodes/*.node (kind: stmt)

// CountedFor is the existing stmt node — already hand-written in mod.rs tests.
// This file will be replaced by build.rs output.

pub(crate) fn all_nodes() -> Vec<(&'static str, crate::shir_nodes::NodeCtor)> {
    vec![
        ("CountedFor", |v| Ok(Box::new(CountedFor::from_json(v)?))),
    ]
}
