import { sh2 } from "/nvme/ai/sh2loop/harness/sh2-namespace.mjs";
sh2._init("/nvme/ai/sh2loop/sh2perl/examples/063_hard_to_parse.sh", []);
sh2._setAllowlist(["/bin/bash","This","file","contains","bash","constructs","that","are","particularly","challenging","to","parse","due","complex","nesting","ambiguous","syntax","and","edge","cases","1.","Deeply","nested","arithmetic","expressions","with","mixed","operators","result","a","+","b","c","-","d","/","e","f","g","h","i","j","k","l","m","n","2.","Complex","array","assignments","expansions","-A","matrix","0","x","y","z","1","index","2","prefix@","3","@","3.","Nested","substitutions","quoting","output","Result:","Nested:","Deep:","Level","4","4.","parameter","expansion","braces","var:-","default:-","fallback:-","computed",":-","default",":0:2","prefix",":0:3","5.","Heredoc","content","cat","EOF","-v","s/","is","comment","Command","substitution","var:-default","6.","pipeline","background","processes","subshells","Starting","Processing","All","done","7.","if","statements","conditions","var","0-9","-f","then","value","5","-q","pattern","condition","met","fi","8.","case","statement","patterns",":upper:",":lower:","in","Double","Single","esac","No","numbers","9.","Function","handling","variables","complex_function","-a","args","options","while","do","--","key","i+1",":-true","flags","flags:j:1","j++","i++","Processed","10.","for","loop","manipulation","threshold","11.","While","commands","IFS","-r","line","-n","counter","max_lines",":space:","Contains","substitution:","expansion:","counter++","input_file","12.","var:-0","index:-0",":-0","13.","chains","Still","level","s/Level/Depth/","-l","14.","redirects","process","diff","file1.txt","file2.txt","comparison.txt","15.","definition","body","define_complex_function","name","16.","test","multiple","-o","-d","dir","-gt","10","passed","17.","brace","1..3","18.","here-string","UPPER:","19.","call","argument","processing","--long-option","spaces","--array-option","item1","item2","item3","--flag","positional","20.","Final","construct","combining","elements","a-z","files","final_result.txt"]);
let counter = 0;
let output = "";
sh2.setVar("result", sh2.arithEval(() => ((sh2.idiv(((Number(sh2.getVar("a")) || 0) + (Number(sh2.getVar("b")) || 0)) * ((Number(sh2.getVar("c")) || 0) - (Number(sh2.getVar("d")) || 0)), sh2.imod(Number(sh2.getVar("e")) || 0, Number(sh2.getVar("f")) || 0)) + ((Number(sh2.getVar("g")) || 0) ** (Number(sh2.getVar("h")) || 0))) - ((Number(sh2.getVar("i")) || 0) << (Number(sh2.getVar("j")) || 0))) | (((Number(sh2.getVar("k")) || 0) & (Number(sh2.getVar("l")) || 0)) ^ ((Number(sh2.getVar("m")) || 0) | (Number(sh2.getVar("n")) || 0)))));
sh2.builtin("declare", ["-A", "matrix"]);
sh2.setVar("matrix[0,0]", ((Number(sh2.getVar("x")) || 0) + (Number(sh2.getVar("y")) || 0)) * (Number(sh2.getVar("z")) || 0));
sh2.setVar("matrix[1,1]", sh2.arrayIndex("array", "${index}"));
sh2.setVar("matrix[2,2]", sh2.arrayItems("prefix"));
sh2.setVar("matrix[3,3]", sh2.arrayLen("array"));
output = String([String(`Result: ${String([String(`Nested: ${String([String(`Deep: ${"Level 4"}`)].join(" ") ?? "").replace(/\u0000/g, "").replace(/\n+$/, "")}`)].join(" ") ?? "").replace(/\u0000/g, "").replace(/\n+$/, "")}`)].join(" ") ?? "").replace(/\u0000/g, "").replace(/\n+$/, "");
process.stdout.write([String(sh2.param(":-", "var", "${default:-${fallback:-$(echo \"computed\")}}"))].join(" ") + "\n");
process.stdout.write([String(sh2.param(":-", "array[${index}]", "${default[@]:0:2}"))].join(" ") + "\n");
sh2.builtin("echo", [sh2.join(sh2.param("slice", "!prefix*", "@", ""))]);
await sh2.pipeline([async () => await sh2.redirect(async () => sh2.builtin("cat", []), [{fd: 0, mode: "heredoc", target: "# This is a comment\n$(echo \"Command substitution\")\n${var:-default}\n$(( 1 + 2 * 3 ))\n", interpolate: false}]), async () => sh2.builtin("grep", ["-v", `^#`]), async () => sh2.builtin("sed", ["s/^/  /"])]);
sh2.background(async () => { await sh2.subshell(async () => { await sh2.exec("sleep", ["1"]); sh2.builtin("echo", [`Starting`]); }); });
sh2.background(async () => { await sh2.subshell(async () => { await sh2.exec("sleep", ["2"]); sh2.builtin("echo", [`Processing`]); }); });
await sh2.exec("wait", []);
process.stdout.write("All done\n");
if ((sh2._g = /^[0-9]+$/.test(String(sh2.getVar("var")))), (sh2.lastExit = sh2._g ? 0 : 1), sh2._g, ((sh2.lastExit === 0) ? ((((((Number(sh2.getVar("var")) || 0) > 0) ? 1 : 0) !== 0) ? ((sh2.lastExit = 0), true) : ((sh2.lastExit = 1), false)), (sh2.lastExit === 0)) : false), ((sh2.lastExit === 0) ? (sh2.test("-f \"$file\""), (sh2.lastExit === 0)) : false)) { if (sh2.test("${array[@]}=~\"value\""), ((sh2.lastExit === 0) ? true : (sh2.builtin("let", ["${#array[@]} > 5"]), (sh2.lastExit === 0)))) { if (sh2.test("\"$(echo \"$var\" | grep -q \"pattern\")\"")) { process.stdout.write("Deeply nested condition met\n"); } else { sh2.lastExit = 0; } } else { sh2.lastExit = 0; } } else { sh2.lastExit = 0; }
{ const $sh_case = String(String(String(sh2.getVar("var"))).toLowerCase() ?? "").replace(/\u0000/g, "").replace(/\n+$/, ""); const $sh_case_v = String($sh_case ?? ""); const $g0 = /^.*[0-9].*/s.exec($sh_case_v); if (($g0 !== null) && ($g0[0].length === $sh_case_v.length)) { { const $sh_case = sh2.param(",,", "var"); if (String($sh_case ?? "").includes("pattern")) { process.stdout.write("Double nested pattern\n"), (sh2.lastExit = 0), true; } else if (true) { process.stdout.write("Single nested pattern\n"), (sh2.lastExit = 0), true; } } } else if (true) { process.stdout.write("No numbers\n"), (sh2.lastExit = 0), true; } }
sh2.functions.set("complex_function", () => { sh2.builtin("local", ["-a", sh2.setArray("args", ["$@"], false)]); sh2.builtin("local", ["-A", sh2.setArray("options", [], true)]); sh2.builtin("local", ["i=0"]); sh2.whileLoopSync(() => sh2.builtin("let", ["i < ${#args[@]}"]), () => { { const $sh_case = sh2.param("", "args[i]"); if (String($sh_case ?? "").startsWith("--")) { sh2.builtin("local", ["key=", sh2.param("#", "args[i]", "--")]); sh2.builtin("local", ["value=", sh2.param(":-", "args[i+1]", "true")]); sh2.setVar("options[\"$key\"]", sh2.getVar("value")); (((sh2.setVar("i", String((Number(sh2.getVar("i")) || 0) + 2)), Number(sh2.getVar("i")) || 0) !== 0) ? ((sh2.lastExit = 0), true) : ((sh2.lastExit = 1), false)); } else if (String($sh_case ?? "").startsWith("-")) { sh2.builtin("local", ["flags=", sh2.param("#", "args[i]", "-")]); sh2.builtin("local", ["j=0"]); { let __sh2_loop_ran = false, __sh2_loop_last = 0; while (sh2.builtin("let", ["j < ${#flags}"])) { __sh2_loop_ran = true; sh2.setVar("options[\"${flags:j:1}\"]", `true`); (((sh2.setVar("j", String((Number(sh2.getVar("j")) || 0) + 1)), ((Number(sh2.getVar("j")) || 0) - 1)) !== 0) ? ((sh2.lastExit = 0), true) : ((sh2.lastExit = 1), false)); __sh2_loop_last = sh2.lastExit; } sh2.lastExit = __sh2_loop_ran ? __sh2_loop_last : 0; } (((sh2.setVar("i", String((Number(sh2.getVar("i")) || 0) + 1)), ((Number(sh2.getVar("i")) || 0) - 1)) !== 0) ? ((sh2.lastExit = 0), true) : ((sh2.lastExit = 1), false)); } else if (true) { sh2.break(); } } }); process.stdout.write([String(`Processed ${sh2.param("slice", "#options", "@", "")} options`)].join(" ") + "\n"), (sh2.lastExit = 0), true; }), true;
sh2.cstyleForSync("i=0; i<${#array[@]}; i++", () => { sh2.cstyleForSync("j=0; j<${#array[i][@]}; j++", () => { if (sh2.builtin("let", ["\u0001SH2GLOB\u0001array[i][j] > threshold"])) { sh2.setVar("result[i]", sh2.arith(" result[i] + array[i][j] ")); } else { sh2.lastExit = 0; } }); });
await sh2.redirect(async () => { sh2.whileLoopSync(() => (sh2.builtin("true", [], {IFS: ""}), sh2.builtin("read", ["-r", "line"]), ((sh2.lastExit === 0) ? ((sh2._g = String(sh2.getVar("line")) !== ""), (sh2.lastExit = sh2._g ? 0 : 1), sh2._g, (sh2.lastExit === 0)) : false), ((sh2.lastExit === 0) ? (((((counter < (Number(sh2.getVar("max_lines")) || 0)) ? 1 : 0) !== 0) ? ((sh2.lastExit = 0), true) : ((sh2.lastExit = 1), false)), (sh2.lastExit === 0)) : false), (sh2.lastExit === 0)), () => { if (/^[[:space:]]*#/.test(String(sh2.getVar("line")))) { sh2.continue(); } else { sh2.lastExit = 0; } { const $sh_case = sh2.getVar("line"); const $sh_case_v = String($sh_case ?? ""); const $g0 = /^.*\$\(.*\).*/s.exec($sh_case_v); const $g1 = /^.*\$\{[^}].*\}.*/s.exec($sh_case_v); const $g2 = /^.*\$\(\(.*\)\).*/s.exec($sh_case_v); if (($g0 !== null) && ($g0[0].length === $sh_case_v.length)) { sh2.builtin("echo", [`Contains command substitution: ${sh2.getVar("line")}`]); } else if (($g1 !== null) && ($g1[0].length === $sh_case_v.length)) { sh2.builtin("echo", [`Contains parameter expansion: ${sh2.getVar("line")}`]); } else if (($g2 !== null) && ($g2[0].length === $sh_case_v.length)) { sh2.builtin("echo", [`Contains arithmetic expansion: ${sh2.getVar("line")}`]); } } ((counter++ !== 0) ? ((sh2.lastExit = 0), true) : ((sh2.lastExit = 1), false)); }); }, [{fd: 0, mode: "herestring", target: await sh2.capture(async () => await sh2.pipeline([async () => sh2.builtin("grep", ["-v", `^#`, sh2.getVar("input_file")]), async () => sh2.builtin("head", ["-n", sh2.getVar("max_lines")])]))}]);
sh2.builtin("eval", [`result=$(( \${var:-0} + \${array[\${index:-0}]:-0} ))`]);
await sh2.pipeline([async () => { await sh2.subshell(async () => await sh2.pipeline([async () => { await sh2.subshell(async () => await sh2.pipeline([async () => { await sh2.subshell(async () => { sh2.builtin("echo", [`Level 3`]); await sh2.subshell(async () => { sh2.builtin("echo", [`Level 4`]); sh2.builtin("echo", [`Still level 4`]); }); }); }, async () => sh2.builtin("grep", [`Level`])])); }, async () => sh2.builtin("sed", ["s/Level/Depth/"])])); }, async () => sh2.builtin("wc", ["-l"])]);
await sh2.redirect(async () => await sh2.exec("diff", [`SH2PS${((await sh2.fs.readFile("file1.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).endsWith("\n") ? (await sh2.fs.readFile("file1.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).slice(0, -1) : await sh2.fs.readFile("file1.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).split("\n").sort().join("\n")}`, `SH2PS${((await sh2.fs.readFile("file2.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).endsWith("\n") ? (await sh2.fs.readFile("file2.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).slice(0, -1) : await sh2.fs.readFile("file2.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).split("\n").sort().join("\n")}`]), [{fd: 0, mode: "herestring", target: ((await sh2.fs.readFile("file1.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).endsWith("\n") ? (await sh2.fs.readFile("file1.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).slice(0, -1) : await sh2.fs.readFile("file1.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).split("\n").sort().join("\n")}, {fd: 0, mode: "herestring", target: ((await sh2.fs.readFile("file2.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).endsWith("\n") ? (await sh2.fs.readFile("file2.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).slice(0, -1) : await sh2.fs.readFile("file2.txt", "utf8").then((r) => ((sh2.lastExit = 0), r)).catch((e) => ((sh2.lastExit = 0), ""))).split("\n").sort().join("\n")}, {fd: 1, mode: "w", target: "comparison.txt"}, {fd: 2, mode: "w", target: "&1"}]);
sh2.functions.set("define_complex_function", () => { sh2.builtin("local", ["name=", sh2.positional[0] ?? ""]); sh2.builtin("local", ["body=", sh2.positional[1] ?? ""]); sh2.builtin("eval", [`${sh2.getVar("name")}() {
        ${sh2.getVar("body")}
    }`]); }), true;
if (sh2.test(" -n \"$var\" -a -f \"$file\" -o -d \"$dir\""), ((sh2.lastExit === 0) ? (sh2.test("\"$(wc -l < \"$file\")\" -gt 10"), (sh2.lastExit === 0)) : false)) { process.stdout.write("Complex test passed\n"); } else { sh2.lastExit = 0; }
process.stdout.write("a1x a1y a1z a2x a2y a2z a3x a3y a3z b1x b1y b1z b2x b2y b2z b3x b3y b3z c1x c1y c1z c2x c2y c2z c3x c3y c3z\n");
await sh2.redirect(async () => sh2.builtin("tr", ["[:upper:]", "[:lower:]"]), [{fd: 0, mode: "herestring", target: String([String(`UPPER: ${sh2.param("^^", "var")}`)].join(" ") ?? "").replace(/\u0000/g, "").replace(/\n+$/, "")}]);
sh2.fnCall("complex_function", ["--long-option=value with spaces", "--array-option", `item1`, `item2`, `item3`, "--flag", `positional argument`, sh2.param(":-", "var", "default"), "computed"]);
await sh2.pipeline([async () => { await sh2.subshell(async () => { if (sh2.test("\"$(echo \"$var\" | tr '[:upper:]' '[:lower:]')\"=~^[a-z]+$")) { sh2.cstyleForSync("i=0; i<${#array[@]}; i++", () => { if (sh2.builtin("let", ["\u0001SH2GLOB\u0001array[i] > threshold"]), ((sh2.lastExit === 0) ? (sh2.test("-f \"${files[i]}\""), (sh2.lastExit === 0)) : false)) { sh2.setVar("result[i]", sh2.arith(" result[i] + $(wc -l < \"${files[i]}\") ")); } else { sh2.lastExit = 0; } }); } else { sh2.lastExit = 0; } }); }, async () => sh2.builtin("sort", ["-n"]), async () => await sh2.redirect(async () => sh2.builtin("tail", ["-n", "5"]), [{fd: 1, mode: "w", target: "final_result.txt"}])]);

await sh2._finish();
